export const FETCH_CURRENCIES_START = "FETCH_CURRENCIES_START";
export const FETCH_CURRENCIES_SUCCESS = "FETCH_CURRENCIES_SUCCESS";
export const FETCH_CURRENCIES_ERROR = "FETCH_CURRENCIES_ERROR";

export const SET_USD_DATA = "SET_USD_DATA";
export const SET_EUR_DATA = "SET_EUR_DATA";
export const SET_RUB_DATA = "SET_RUB_DATA";
export const CHART_START = "CHART_START";
export const CHART_SUCCESS = "CHART_SUCCESS";
export const CHART_ERROR = "CHART_ERROR";

export const SET_DATA_IN_DATA_BASE = "SET_DATA_IN_DATA_BASE";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_USERNAME = "SET_USERNAME";
export const ERROR_INPUT_HANDLER = "ERROR_INPUT_HANDLER";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
